# Generated by Django 3.1.5 on 2021-02-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideaset', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profile/', verbose_name='photo'),
        ),
    ]
